#!/bin/bash
IFS='LINUXMACHINEIP'
FINDOUT=$1
#REG='$'
FINOUTREG=$FINDOUT$REG
OUTFILENAME=$2
SERVEROUTFILE=$3
for i in $(cat in1.txt);do
        echo $i | grep "$FINDOUT$REG" &> /dev/null
        if [[ $? -eq 0 ]];then
              echo $i >> $OUTFILENAME.tmp
              head -1 $OUTFILENAME.tmp >> $SERVEROUTFILE
              cat $OUTFILENAME.tmp >> $OUTFILENAME
              rm $OUTFILENAME.tmp
        fi
done
