#!/bin/bash
INPUT_FILE='list2'

for i in $(cat $INPUT_FILE);do
        echo $i >  $INPUT_FILE.tmp
        sleep 1
        IFS=','

        while read IP MOUNT
                do
                        echo "Scanning for $IP:"
                        ssh -i id_rsa -l anurags $IP "ps -ef | grep $MOUNT"
                done < $INPUT_FILE.tmp

        IFS="\n"
done
